# Cel

Celem tego dokumentu jest sprawdzenie danych do MVP dla gminy Imielin. W szczególności:
- dostępności danych dla różnych lat
- jakości danych

In [1]:
import pandas as pd

## Rodzaj zabudowy

## Rozwój zabudowy w ostatnich latach

## Ilość terenów zielonych

In [3]:
df = pd.read_csv('data/Imielin TERENY ZIELENI.csv')
df

,Rok,TERENY ZIELENI/Rodzinne ogrody działkowe/ogrody liczba,TERENY ZIELENI/Rodzinne ogrody działkowe/ogrody powierzchnia,TERENY ZIELENI/Rodzinne ogrody działkowe/działki liczba,TERENY ZIELENI/Rodzinne ogrody działkowe/działki powierzchnia,TERENY ZIELENI/Tereny zieleni wg lokalizacji w powiatach/parki spacerowo - wypoczynkowe powierzchnia w miastach,TERENY ZIELENI/Tereny zieleni wg lokalizacji w powiatach/zieleńce powierzchnia w miastach,TERENY ZIELENI/Tereny zieleni wg lokalizacji w powiatach/zieleń uliczna powierzchnia w miastach,TERENY ZIELENI/Tereny zieleni wg lokalizacji w powiatach/tereny zieleni osiedlowej powierzchnia w miastach,"TERENY ZIELENI/Tereny zieleni wg lokalizacji w powiatach/parki, zieleńce i tereny zieleni osiedlowej powierzchnia w miastach",TERENY ZIELENI/Tereny zieleni wg lokalizacji w powiatach/cmentarze powierzchnia w miastach
0,1996,0.4,NaN,NaN,NaN,NaN,NaN,0.4,NaN,NaN,NaN
1,1997,0.4,NaN,NaN,NaN,NaN,NaN,0.4,NaN,NaN,NaN
2,1998,0.4,1.2,4.6,1.0,NaN,NaN,0.4,1.0,3500.0,NaN
3,1999,0.4,1.2,4.6,1.0,NaN,NaN,0.4,1.0,3500.0,NaN
4,2000,0.4,1.2,4.6,1.0,NaN,NaN,0.4,1.0,3500.0,NaN
5,2001,0.4,1.2,4.6,1.0,NaN,NaN,0.4,1.0,3500.0,NaN
6,2002,0.4,1.2,4.6,1.0,NaN,NaN,0.4,1.0,3500.0,NaN
7,2003,0.4,1.2,4.6,1.0,NaN,NaN,0.4,1.0,3500.0,NaN
8,2004,NaN,NaN,NaN,NaN,0.4,1.2,0.4,2.0,NaN,3500.0
9,2005,NaN,NaN,NaN,NaN,0.4,1.2,0.4,2.0,NaN,3500.0
10,2006,NaN,NaN,NaN,NaN,0.4,1.2,0.4,2.0,NaN,3500.0
11,2007,NaN,NaN,NaN,NaN,0.4,1.2,0.4,2.0,NaN,3500.0
12,2008,NaN,NaN,NaN,NaN,0.4,1.2,0.4,2.0,NaN,3500.0
13,2009,NaN,NaN,NaN,NaN,0.4,1.2,0.4,2.0,NaN,3500.0
14,2010,NaN,NaN,NaN,NaN,0.4,1.2,0.4,2.0,NaN,3500.0
15,2011,NaN,NaN,NaN,NaN,0.4,1.2,0.4,2.0,NaN,3500.0
16,2012,NaN,NaN,NaN,NaN,0.4,1.2,0.4,2.0,NaN,3500.0
17,2013,NaN,NaN,NaN,NaN,0.4,1.2,0.4,2.0,NaN,3500.0
18,2014,NaN,NaN,NaN,NaN,0.4,1.2,0.4,2.0,NaN,3500.0
19,2015,NaN,NaN,NaN,NaN,0.4,1.2,0.4,2.0,NaN,3500.0
20,2016,NaN,NaN,NaN,NaN,0.4,1.2,0.4,2.0,NaN,3500.0
21,2017,NaN,NaN,NaN,NaN,0.4,1.2,0.4,2.0,NaN,3500.0
22,2018,NaN,NaN,NaN,NaN,0.4,1.2,0.4,2.0,NaN,3500.0

Dla porównania wrzucam podobne dane z Kielc.

In [2]:
df = pd.read_csv('data/Kielce TERENY ZIELENI.csv', index_col='Rok')
df

,TERENY ZIELENI/Rodzinne ogrody działkowe/ogrody liczba,TERENY ZIELENI/Rodzinne ogrody działkowe/ogrody powierzchnia,TERENY ZIELENI/Rodzinne ogrody działkowe/działki liczba,TERENY ZIELENI/Rodzinne ogrody działkowe/działki powierzchnia,TERENY ZIELENI/Tereny zieleni wg lokalizacji w powiatach/parki spacerowo - wypoczynkowe powierzchnia w miastach,TERENY ZIELENI/Tereny zieleni wg lokalizacji w powiatach/zieleńce powierzchnia w miastach,TERENY ZIELENI/Tereny zieleni wg lokalizacji w powiatach/zieleń uliczna powierzchnia w miastach,TERENY ZIELENI/Tereny zieleni wg lokalizacji w powiatach/tereny zieleni osiedlowej powierzchnia w miastach,"TERENY ZIELENI/Tereny zieleni wg lokalizacji w powiatach/parki, zieleńce i tereny zieleni osiedlowej powierzchnia w miastach",TERENY ZIELENI/Tereny zieleni wg lokalizacji w powiatach/cmentarze powierzchnia w miastach
Rok,,,,,,,,,,
2004,62.40,7.00,135.0,176.10,245.50,NaN,102.50,8.0,8.0,NaN
2005,62.40,7.00,135.0,304.70,374.10,43.60,102.50,8.0,8.0,12.0
2006,62.40,7.00,140.0,304.70,374.10,43.60,102.50,8.0,8.0,12.0
2007,62.40,7.00,140.0,254.00,323.40,43.60,102.50,8.0,8.0,12.0
2008,62.40,7.00,140.0,254.00,323.40,43.60,84.00,8.0,8.0,12.0
2009,62.40,9.60,140.0,246.70,318.70,43.60,84.00,8.0,8.0,12.0
2010,62.40,9.60,140.0,246.70,318.70,43.60,82.00,8.0,8.0,12.0
2011,62.40,9.60,140.0,263.00,335.00,43.60,79.00,8.0,8.0,12.0
2012,67.30,9.60,140.0,263.00,339.90,43.60,79.00,8.0,8.0,12.0
2013,72.95,5.98,140.0,251.74,330.67,43.60,79.00,9.0,7.0,12.0
2014,72.95,4.58,140.0,251.74,329.27,43.60,80.55,9.0,6.0,12.0
2015,72.95,4.58,140.0,258.15,335.68,43.60,80.93,9.0,6.0,12.0
2016,72.85,5.58,140.0,246.90,325.33,47.53,80.93,9.0,6.0,12.0
2017,71.00,5.71,140.0,246.90,323.61,47.53,82.20,9.0,8.0,12.0
2018,69.14,5.47,140.0,246.69,321.30,47.75,80.19,8.0,7.0,12.0

## Sport i rekreacja

In [5]:
df = pd.read_csv('data/Imielin ŚCIEŻKI ROWEROWE.csv')
df

,Rok,ŚCIEŻKI ROWEROWE/Długość ścieżek rowerowych (dróg dla rowerów)/ścieżki rowerowe (drogi dla rowerów) ogółem,ŚCIEŻKI ROWEROWE/Długość ścieżek rowerowych (dróg dla rowerów)/ścieżki rowerowe na 10 tys. km2,ŚCIEŻKI ROWEROWE/Długość ścieżek rowerowych (dróg dla rowerów)/ścieżki rowerowe na 10 tys. ludności,ŚCIEŻKI ROWEROWE/Długość ścieżek rowerowych (dróg dla rowerów)/będących pod zarządem urzędu marszałkowskiego,ŚCIEŻKI ROWEROWE/Długość ścieżek rowerowych (dróg dla rowerów)/będących pod zarządem starostwa,ŚCIEŻKI ROWEROWE/Długość ścieżek rowerowych (dróg dla rowerów)/będących pod zarządem gminy,ŚCIEŻKI ROWEROWE/Długość ścieżek rowerowych (dróg dla rowerów)/ścieżki rowerowe na 100 km2
0,2012,2.4,857.4,2.81,NaN,NaN,NaN,8.57
1,2013,1.3,464.5,1.51,1.3,NaN,NaN,4.64
2,2014,1.3,464.5,1.49,1.3,NaN,NaN,4.64
3,2015,3.7,1321.9,4.18,1.3,NaN,2.4,13.22
4,2016,3.7,1321.9,4.16,1.3,NaN,2.4,13.22
5,2017,3.7,1321.9,4.09,1.3,NaN,2.4,13.22
6,2018,5.3,1893.5,5.79,1.3,4.0,NaN,18.94

In [13]:
df[['ŚCIEŻKI ROWEROWE/Długość ścieżek rowerowych (dróg dla rowerów)/ścieżki rowerowe na 10 tys. km2', 
    'ŚCIEŻKI ROWEROWE/Długość ścieżek rowerowych (dróg dla rowerów)/ścieżki rowerowe na 10 tys. ludności']]

,ŚCIEŻKI ROWEROWE/Długość ścieżek rowerowych (dróg dla rowerów)/ścieżki rowerowe na 10 tys. km2,ŚCIEŻKI ROWEROWE/Długość ścieżek rowerowych (dróg dla rowerów)/ścieżki rowerowe na 10 tys. ludności
0,857.4,2.81
1,464.5,1.51
2,464.5,1.49
3,1321.9,4.18
4,1321.9,4.16
5,1321.9,4.09
6,1893.5,5.79

In [4]:
df = pd.read_csv('data/Imielin SPORT.csv')
df

,Rok,SPORT/Kluby sportowe łącznie z klubami wyznaniowymi i UKS/ćwiczący ogółem,SPORT/Kluby sportowe łącznie z klubami wyznaniowymi i UKS/ćwiczący kobiety,SPORT/Kluby sportowe łącznie z klubami wyznaniowymi i UKS/trenerzy,SPORT/Kluby sportowe łącznie z klubami wyznaniowymi i UKS/kluby,SPORT/Kluby sportowe łącznie z klubami wyznaniowymi i UKS/sekcje sportowe,SPORT/Kluby sportowe łącznie z klubami wyznaniowymi i UKS/instruktorzy sportowi,SPORT/Kluby sportowe łącznie z klubami wyznaniowymi i UKS/ćwiczący do lat 18 ogółem,SPORT/Kluby sportowe łącznie z klubami wyznaniowymi i UKS/członkowie,SPORT/Kluby sportowe łącznie z klubami wyznaniowymi i UKS/inne osoby prowadzące zajęcia sportowe,SPORT/Kluby sportowe łącznie z klubami wyznaniowymi i UKS/ćwiczący do lat 18 dziewczęta
0,2010,19.0,7.0,1.0,1.0,1.0,1.0,18.0,19.0,NaN,6.0
1,2012,130.0,14.0,5.0,2.0,4.0,1.0,90.0,140.0,NaN,14.0
2,2014,24.0,8.0,1.0,1.0,4.0,1.0,24.0,30.0,NaN,8.0
3,2016,207.0,152.0,5.0,3.0,7.0,6.0,184.0,250.0,2.0,134.0
4,2018,329.0,103.0,12.0,3.0,6.0,2.0,286.0,345.0,3.0,102.0

## Infrastruktura drogowa

## Łatwość dojazdu do/z wybranego miejsca

## Usługi

## Środowisko

## Zasięg

## Edukacja

## Rozwój gminy

## Nieruchomości